##############################
# Please edit this line to "not_sample_anymore" to make the bot run
not_sample_anymore: "Ahhhhhhhhhhh i am not blind so i'll follow what the line above me asked"
##############################
bot_token: "1261517257:AAHNOaZS6AkPIGvzO_9fOapJA9mN1PDlpy4"
owner_id: 935046373
owner_username: "Denver02"
database_url: "postgres://username:password@host:5432/database_name"
message_dump: "-1001301090623"
load: []
no_load: []
strict_antispam: False
workers: 4
allow_excl: False
deepfry_token: None
del_cmds: False
sw_api: ''

# Permission
sudo_users: [935046373]
support_users: [935046373]
whitelist_users: [935046373]
